### ISSUE TITLE
Issue while downloading the background video

### ISSUE THREAD

**Issue by dinornall** [elebumm/RedditVideoMakerBot#1057]
**To Reproduce**
I just ran the program, following the documentation

**Expected behavior**
I expected the program to run without an issue

**Screenshots**
<img width="720" alt="Screenshot 2022-07-22 at 12 52 14 AM" src="https://user-images.githubusercontent.com/108722968/180365313-313ccf71-7569-464f-a9b0-5328efd4e192.png">

<img width="682" alt="Screenshot 2022-07-22 at 12 52 40 AM" src="https://user-images.githubusercontent.com/108722968/180365362-137f6c3b-3232-4457-a88a-de056d364d88.png">

<img width="680" alt="Screenshot 2022-07-22 at 12 52 53 AM" src="https://user-images.githubusercontent.com/108722968/180365392-f6396b32-1d2c-4485-a8ce-978ec3a1337b.png">

<img width="676" alt="Screenshot 2022-07-22 at 12 53 05 AM" src="https://user-images.githubusercontent.com/108722968/180365413-a1db2669-f924-4bb2-88f4-2e7a8f18ca17.png">

**System (please complete the following information):**

- Python Version: 3.10.4
- OS: macOS Monterey
- App version / Branch: 2.3

**Additional context**
I ran the program a few times, attempted reinstalling, and only once did a different issue come up, but it was quickly followed by this one again

**Comment by Anvilator-web** [comment]
Seems like a problem is occurring I'm your python installation itself

**Comment by Anvilator-web** [comment]
Okay, looking at the error, it seems like python can't verify the ssl certificate. I haven't seen this error before. Did python fail to verify youtube's certification?

**Comment by Anvilator-web** [comment]
Maybe reinstall python?

**Comment by dinornall** [comment]
Alright, I'll try it

**Comment by dinornall** [comment]
That didn't seem to work

**Comment by The-web-wolf** [comment]
Got the same error, 
Trying from Mac OS, Monterey 12.4. 
python3 3.10.4

**Comment by The-web-wolf** [comment]
After some research, it turns out it has nothing to do with the code as @Anvilator-web hinted, It is typically a MacOS issue whereby noo SSL cert is used by Python to make requests. 
Anyways running this single command worked for me

`ln -s /etc/ssl/* /Library/Frameworks/Python.framework/Versions/3.10/etc/openssl`

Another approach would be to look at Certifi, [Certify](https://pypi.org/project/certifi/) , _I couldn't manage to get it to work for me, but might for you_

Alternatively, if you should should replace "https" with "http" in `background.py`, should work as well, **not recommended**

You can read more here more suggestions [StackOverflow - python certificate fail](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate)

Cheers!

**Comment by Anvilator-web** [comment]
Ooh that's interesting. I haven't worked much with macOS so that isn't my area of expertise

**Comment by JasonLovesDoggo** [comment]
https://stackoverflow.com/a/58525755
