### ISSUE TITLE
[Bug]: Invalid Syntax

### ISSUE THREAD

**Issue by mrawesomey** [elebumm/RedditVideoMakerBot#1199]
### Describe the bug

![Image](https://user-images.githubusercontent.com/106691142/186004239-61881db1-9832-4424-8edb-7653409adaf9.png)
This happens and I've already downloaded all modules

### Reproduction Steps

I typed python3 main.py

### Expected behavior

That it started the program

### Screenshots

![image](https://user-images.githubusercontent.com/106691142/186004629-3145a6cc-ec01-4911-86b8-53f637225be4.png)

### System Information

Operating System : Windows 10
Python version : Python 3.10.6
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ThisNameWasTaken** [comment]
I also had the same issue and I looked through the docs. 

It turns out we need python 3.10 for the master branch. https://reddit-video-maker-bot.netlify.app/docs/prerequisites#if-it-returns-the-following-output-and-you-are-using-master

I installed it from the microsoft store and ran the commands with `python3.10` instead of `python` or `python3` (python3.10 -m playwright install). I also uninstalled python 3.9, but I guess you can also keep the older versions if you need them.

**Comment by mrawesomey** [comment]
Thx but now even tho I have config.toml filled out it says 
![image](https://user-images.githubusercontent.com/106691142/186019912-1724bee4-8d16-40b3-a0fe-b051e7b7ac2c.png)
