### ISSUE TITLE
How to change the voice to male

### ISSUE THREAD

**Issue by Khal-ID** [elebumm/RedditVideoMakerBot#15]
This is not an issue, as the title says, is there a way to change the TTS voice to male? If so how? If not, maybe you could add in the option? Thank you!

**Comment by JasonLovesDoggo** [comment]
I don't believe so but there is always
TTS.setPitch()
Either way I'm currently almost done on a redesign of that module using the TikTok TTS API versus the Google One

**Comment by JasonLovesDoggo** [comment]
I don't believe so but there is always
TTS.setPitch()
Either way I'm currently almost done on a redesign of that module using the TikTok TTS API versus the Google One (in my fork)

**Comment by JasonLovesDoggo** [comment]
update: I'm done with the redesign and it's a drop-in replacement if anyone wants to use it.

[TTSwrapper](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/blob/master/video_creation/TTSwrapper.py)
and [voices.py](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/blob/master/video_creation/voices.py)

**Comment by Khal-ID** [comment]
I'll definitely give it a try tomorrow. Thank you! :)

**Comment by elebumm** [comment]
The google TTS isn't very robust (which is currently being used). 
I used this because it requires almost no configuration.

I have a branch up that uses the Google Cloud Text to speech service where you can choose what voice you would like:
https://cloud.google.com/text-to-speech/docs/voices

The only drawback is this requires a bit more configuration and to have Google Cloud.

**Comment by IdkHowAreYOU** [comment]
How can i use one of the voices from Google Cloud?
