### ISSUE TITLE
[Bug]: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by 88Q** [elebumm/RedditVideoMakerBot#1653]
### Describe the bug

after background video has been chopped it gives me [WinError 2] The system cannot find the file specified

### Reproduction Steps

everything downloads successfully and the video chops but it doesnt output final vid

### Expected behavior

![ApplicationFrameHost_CfuZxSBoLu](https://github.com/elebumm/RedditVideoMakerBot/assets/74650963/5845474e-c57b-40f2-a7b1-92f669e09c4c)

### System Information

Operating System : Windows 11
Python version : python 3.1
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SiouxxieSixxsta** [comment]
this might be due to how imagemagick/moviepy is installed (another debug would be to install image magick). you can maybe be able to fix this by using a virtual environment and after installing all the requirements/libraries you can go into venv/lib/sitpackages/moviepy and go into config_defaults.py. Next scroll down to "IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'auto-detect')" and replace it with "IMAGEMAGICK_BINARY = "C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick.exe"" replace the path with the path to YOUR image magick exe file path  and make sure there are two slashes when you paste your path. Lastly run the main py file and it should have fixed it. Hopefully that helped.
