### ISSUE TITLE
no module named utils.console

### ISSUE THREAD

**Issue by p1x3lll** [elebumm/RedditVideoMakerBot#173]
when i run `python3 main.py` this happens

`C:\Users\doesntmatter\Desktop\RedditVideoMakerBot>python3 main.py
Traceback (most recent call last):
  File "C:\Users\doesntmatter\Desktop\RedditVideoMakerBot\main.py", line 1, in <module>
    from utils.console import print_markdown
ModuleNotFoundError: No module named 'utils.console'`

**Comment by p1x3lll** [comment]
ok i renamed utils to utils.console that fixed it

**Comment by v6r** [comment]
> ok i renamed utils to utils.console that fixed it

i have the same error. What exact did you do. I dont understand it.

**Comment by EthanToews** [comment]
> i have the same error. What exact did you do. I dont understand it.

For anyone still having this issue.
I found out (for me at least) the utils.console dir was not importing correctly within the main.py file
stack overflow helped out with this: https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

turns out I had to include a '__init__.py' empty file within the utils directory, then ran the script again and all is well now.
