### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by juanbahena9** [elebumm/RedditVideoMakerBot#1738]
### Summary

Bot not available with Python 3.11

### Is your feature request related to a problem?

Do you guys have a new version of the bot that is compatible with Python 3.11?

### Describe the solution you'd like

Make it compatible with Python 3.11.

**Comment by Toretto99** [comment]
Hi there, you can change the line ( 83 ) in the main.py file, instead of ` if sys.version_info.major != 3 or sys.version_info.minor != 10:` to ` if sys.version_info.major != 3 or sys.version_info.minor != 11: ` (as can be seen in the attached screenshot), based on my few testings , this seems to work fine, although I haven't conducted extensive testing to catch potential edge cases.

<img width="1347" alt="Screenshot 2023-07-09 at 11 19 44" src="https://github.com/elebumm/RedditVideoMakerBot/assets/117114759/70ddf0d5-5047-4254-8f17-bc0555f910d8">

This could be a quick solution for those who wish to use Python 3.11, but keep in mind that the original contributors have recommended using Python 3.10, as the version has been more tested.

**Comment by juanbahena9** [comment]
Thank you for reaching out. I have tried doing the changes but the main.oh
file only opens for a split second on Python and then disappears. Any
suggestions?

**Comment by Toretto99** [comment]
>
 
I am sorry but I do not understand what you mean saying that your file opens and then disappears. Could you please provide the details you see in the terminal when you run it?

**Comment by sarimwaniR** [comment]
.

**Comment by JasonLovesDoggo** [comment]
> Hi there, you can change the line ( 83 ) in the main.py file, instead of ` if sys.version_info.major != 3 or sys.version_info.minor != 10:` to `if sys.version_info.major != 3 or sys.version_info.minor != 11:` (as can be seen in the attached screenshot), based on my few tests , this seems to work fine, although I haven't conducted extensive testing to catch potential edge cases.
> 
> <img alt="Screenshot 2023-07-09 at 11 19 44" width="1347" src="https://private-user-images.githubusercontent.com/117114759/252136648-70ddf0d5-5047-4254-8f17-bc0555f910d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTEwMDAsIm5iZiI6MTcwNjQ1MDcwMCwicGF0aCI6Ii8xMTcxMTQ3NTkvMjUyMTM2NjQ4LTcwZGRmMGQ1LTUwNDctNDI1NC04ZjE3LWJjMDU1NWY5MTBkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNDA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzMzMmViYTQxMjBhNmY0ZmZkZTM3NTQ0MjA3YWJlMzhhMDVjOWU1ZWUwNWNjNWMyYzcwM2E5MTM5ODlmZDU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BCXfqCu0zgJU3X6Zjfg4ED40zaWR7Gg9ayVywV7Rdxs">
> This could be a quick solution for those who wish to use Python 3.11, but keep in mind that the original contributors have recommended using Python 3.10, as the version has been more tested.

The reason is that for some of our dependencies which we use for some features, py310 is the latest supported.
