### ISSUE TITLE
Help me the resolv this error

### ISSUE THREAD

**Issue by ArielKloehn** [elebumm/RedditVideoMakerBot#2037]
### Describe the bug

![CWindowsSystem32cmd exe](https://github.com/elebumm/RedditVideoMakerBot/assets/168828816/04fb767a-0a39-4d40-bc5c-3fe93d03aab7)

### Reproduction Steps

![CWindowsSystem32cmd exe](https://github.com/elebumm/RedditVideoMakerBot/assets/168828816/5e886e5c-a0ab-4233-94ad-8d008529693b)

### Expected behavior

.

### Screenshots

![CWindowsSystem32cmd exe](https://github.com/elebumm/RedditVideoMakerBot/assets/168828816/af484f2e-ff99-4633-ac3a-7a1bce5ec995)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

.

**Comment by vellovic** [comment]
use python 3.10

**Comment by meetVaidya** [comment]
so it specifically needs python version 3.10 ?

**Comment by ItzKeon** [comment]
the version of python must be within 3.10.x, so as long as your version has 3.10 in it then it should work fine.

**Comment by easy-peasy** [comment]
As others said use python 3.10 (or 3.11 as per https://github.com/elebumm/RedditVideoMakerBot/pull/2028) 
Some of the project dependencies (listed in requirements.txt) are not available yet in python 3.12 and 3.13.

Also please use more specific semantically meaningful naming when submitting issues for easier navigation, for example this issue could have been called "Compilation problem installing requirements on Windows 11 and Python 3.6" instead of "Help me resolve this error"
