### ISSUE TITLE
When it tries to render the video...

### ISSUE THREAD

**Issue by ahjahahhahahd** [elebumm/RedditVideoMakerBot#314]
![image](https://user-images.githubusercontent.com/106915713/172059803-3c2dad9e-953d-47a3-b673-da52958b1e0c.png)

**Comment by The-Drobe** [comment]
I had a similar issue. It was caused by the code trying to use ImageMagick ffmeg instead of the one that the code auto-downloads. 

I had to uninstall it I presume that you are on windows according to your log. You can uninstall it by pressing `WIN + R` typing in `control` > Under programs click on uninstall a program > search for `ImageMagick` > right click then hit uninstall 

You could also check if FFmpeg is installed by `WIN + R` type `cmd` then type `where ffmpeg` if it returns nothing it is not installed but if it returns something like `C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\ffmpeg.exe` it is installed.

**Comment by JasonLovesDoggo** [comment]
Closed for inactivity
Please reopen if you still have a problem
