### ISSUE TITLE
Cookies popup on redidit post screenshot

### ISSUE THREAD

**Issue by lothaen20** [elebumm/RedditVideoMakerBot#39]
![comment_0](https://user-images.githubusercontent.com/49908589/171372907-36cda13d-2466-4951-aa89-136507e16e78.png)

As you can see the prompt to accept or reject cookies shows up and gets in the way of the post. Any ideas on how to bypass that?

**Comment by FreebieII** [comment]
Maybe try going on Reddit on the browser that you are using for playwright, and Accept All manually

**Comment by nmarotte** [comment]
change
`from playwright.sync_api import sync_playwright` to `from playwright.sync_api import sync_playwright, ViewportSize`
and right after `page.goto(reddit_object["thread_url"])` add on a new line `page.set_viewport_size(ViewportSize(width=1920, height=1080))`. This should set your fake browser in full screen so that the accept all is outside of the sceenshot
