### ISSUE TITLE
Error when getting subreddit

### ISSUE THREAD

**Issue by mohandabc** [elebumm/RedditVideoMakerBot#6]
So I had one of the issues already solved by installing playwright. But after that I get this error

![image](https://user-images.githubusercontent.com/9198732/171268287-621e9cd2-8acb-444b-bd9b-765459ce067b.png)

**Comment by owengaspard** [comment]
It looks like Reddit timed out. Check if your .env variables are right and if you can access Reddit like normal. Also, check to see if you have the latest version pulled.

I had that same issue with playwright that you had before. After installing it, I had to run `playwright install-deps`. I see you aren’t getting that error, but that may help too.

**Comment by owengaspard** [comment]
Huh, that's weird. I'm not sure why it doesn't work in the venv. Mine wouldn't either, but that's for a completely different reason with my current configuration and nothing to do with this repo. I just assumed that it is an issue with being unable to access Reddit because of the error code it gave.

**Comment by mohandabc** [comment]
Well, Thank you anyway, it works like this for now, I look into it later, thanks again

**Comment by elebumm** [comment]
Glad it works. Closing this issue. Feel free to open again if this continues!
