### ISSUE TITLE
system crash

### ISSUE THREAD

**Issue by Sadid57** [elebumm/RedditVideoMakerBot#767]
![Screenshot 2022-06-30 183620](https://user-images.githubusercontent.com/108466620/176678810-2673d609-6fc2-4122-bca1-2ac0065f9486.png)

**Comment by Cizzl** [comment]
Maybe try to delete the temp folder and try again

**Comment by JasonLovesDoggo** [comment]
Do you have sox installed and added to path?

**Comment by NHastings2** [comment]
Hi @Sadid57 , Recently the creator of the TTS site added a rate limit to the AWS server. After about 20 request, there is a 60 second wait before you can submit more requests. I'm currently working on a patch that will add a wait when the rate is reached so that longer comment threads can be reached.

**Comment by JasonLovesDoggo** [comment]
update to develop!
