### ISSUE TITLE
RedditVideoMakerBot-2.2.2 - Line 47 in final_video.py 

### ISSUE THREAD

**Issue by Sjpretorius1** [elebumm/RedditVideoMakerBot#868]
is: audio_clips = [AudioFileClip(f"assets/mp3/{i}.mp3") for i in range(number_of_clips)]

should be: audio_clips = [AudioFileClip(f"assets/temp/mp3/{i}.mp3") for i in range(number_of_clips)]

**Comment by William9923** [comment]
Hi, @Sjpretorius1 this issue is fixed in develop branch. When the new version is released, i think this issue (v2.2.2) should not persist.

Bump to @JasonLovesDoggo or @CallumIO to close this issue after releasing the newest version & making sure this issue not occuring anymore (i think this cause a lot , but please correct me if im wrong)
![image](https://user-images.githubusercontent.com/45505811/177573886-65fb1c9a-06b7-406a-91cc-399b5b59dc61.png)
