### ISSUE TITLE
Main.py Module not found

### ISSUE THREAD

**Issue by ArtemisFowl592** [elebumm/RedditVideoMakerBot#9]
I am having trouble getting the main.py to run - could anyone assist?

PS C:\Users\Dave Spottiswoode\AppData\Local\Programs\Python\Python310> .\python main.py
Traceback (most recent call last):
  File "C:\Users\Dave Spottiswoode\AppData\Local\Programs\Python\Python310\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "C:\Users\Dave Spottiswoode\AppData\Local\Programs\Python\Python310\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
PS C:\Users\Dave Spottiswoode\AppData\Local\Programs\Python\Python310>

**Comment by owengaspard** [comment]
In the directory of the repository, run `python3 -m pip install -r requirements.txt`.

**Comment by Antartiida** [comment]
I am getting the same error, ModuleNotFoundError: No module named 'rich'
I ran the command you mentioned, but it didnt ran as python3, i had to run it like this: 

python -m pip install -r requirements.txt

Here's the output: 
PS C:\Users\camus\Desktop\Tikitaka> python -m pip install -r requirements.txt
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting black==20.8b1
  Using cached black-20.8b1-py3-none-any.whl
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.12
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting commonmark==0.9.1
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting flake8==3.8.3
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting greenlet==1.1.2
  Using cached greenlet-1.1.2-cp310-cp310-win_amd64.whl (101 kB)
Collecting gTTS==2.2.4
  Using cached gTTS-2.2.4-py3-none-any.whl (26 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imageio==2.19.2
  Using cached imageio-2.19.2-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7
  Using cached imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting mutagen==1.45.1
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
Collecting pathspec==0.8.0
  Using cached pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting Pillow==9.1.1
  Using cached Pillow-9.1.1-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting playwright==1.22.0
  Using cached playwright-1.22.0-py3-none-win_amd64.whl (26.5 MB)
Collecting praw==7.6.0
  Using cached praw-7.6.0-py3-none-any.whl (188 kB)
Collecting prawcore==2.3.0
  Using cached prawcore-2.3.0-py3-none-any.whl (16 kB)
Collecting proglog==0.1.10
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyee==8.1.0
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting Pygments==2.12.0
  Using cached Pygments-2.12.0-py3-none-any.whl (1.1 MB)
Collecting python-dotenv==0.20.0
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting pytube==12.1.0
  Using cached pytube-12.1.0-py3-none-any.whl (56 kB)
Collecting regex==2020.10.15
  Using cached regex-2020.10.15.tar.gz (690 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting rich==12.4.4
  Using cached rich-12.4.4-py3-none-any.whl (232 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting toml==0.10.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting tqdm==4.64.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting typed-ast==1.4.1
  Using cached typed_ast-1.4.1.tar.gz (208 kB)
  Preparing metadata (setup.py) ... done
Collecting typing_extensions==4.2.0
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting update-checker==0.18.0
  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting websocket-client==1.3.2
  Using cached websocket_client-1.3.2-py3-none-any.whl (54 kB)
Collecting websockets==10.1
  Using cached websockets-10.1-cp310-cp310-win_amd64.whl (97 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Using legacy 'setup.py install' for moviepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for regex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for typed-ast, since package 'wheel' is not installed.
Installing collected packages: typed-ast, toml, regex, pyee, mypy-extensions, mccabe, commonmark, certifi, appdirs, websockets, websocket-client, urllib3, typing_extensions, six, pytube, python-dotenv, Pygments, pyflakes, pycodestyle, Pillow, pathspec, numpy, mutagen, imageio-ffmpeg, idna, greenlet, decorator, colorama, click, charset-normalizer, tqdm, rich, requests, playwright, imageio, flake8, black, update-checker, proglog, prawcore, gTTS, praw, moviepy
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error

  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast27.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast3.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\conversions.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\__init__.py -> build\lib.win-amd64-3.10\typed_ast
      package init file 'ast3\tests\__init__.py' not found (or not a regular file)
      creating build\lib.win-amd64-3.10\typed_ast\tests
      copying ast3\tests\test_basics.py -> build\lib.win-amd64-3.10\typed_ast\tests
      running build_ext
      building '_ast27' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\camus\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by owengaspard** [comment]
I'm not sure if this is actually required, but in that log, it says an error is that Microsoft Visual Studio C++ Build Tools are required. Try installing it with the link it provides (https://visualstudio.microsoft.com/visual-cpp-build-tools/)

**Comment by JasonLovesDoggo** [comment]
I can't really help you here because I installed those tools for different
project. But I mean I wasn't getting the error.

**Comment by JasonLovesDoggo** [comment]
I can't really help you heal because I installed the tools for a different project on my computer but I mean I wasn't getting the error.

**Comment by Antartiida** [comment]
Weird, i installed visual CPP build tools as it was mentioning first, now its showing this error, not sure if should place the whole output but here it is. 
##################################################
C:\Users\camus\Desktop\Tikitaka>python -m pip install -r requirements.txt
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting black==20.8b1
  Using cached black-20.8b1-py3-none-any.whl
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.12
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting commonmark==0.9.1
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting flake8==3.8.3
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting greenlet==1.1.2
  Using cached greenlet-1.1.2-cp310-cp310-win_amd64.whl (101 kB)
Collecting gTTS==2.2.4
  Using cached gTTS-2.2.4-py3-none-any.whl (26 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imageio==2.19.2
  Using cached imageio-2.19.2-py3-none-any.whl (3.4 MB)
Collecting imageio-ffmpeg==0.4.7
  Using cached imageio_ffmpeg-0.4.7-py3-none-win_amd64.whl (22.6 MB)
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting mutagen==1.45.1
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
Collecting pathspec==0.8.0
  Using cached pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting Pillow==9.1.1
  Using cached Pillow-9.1.1-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting playwright==1.22.0
  Using cached playwright-1.22.0-py3-none-win_amd64.whl (26.5 MB)
Collecting praw==7.6.0
  Using cached praw-7.6.0-py3-none-any.whl (188 kB)
Collecting prawcore==2.3.0
  Using cached prawcore-2.3.0-py3-none-any.whl (16 kB)
Collecting proglog==0.1.10
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyee==8.1.0
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting Pygments==2.12.0
  Using cached Pygments-2.12.0-py3-none-any.whl (1.1 MB)
Collecting python-dotenv==0.20.0
  Using cached python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Collecting pytube==12.1.0
  Using cached pytube-12.1.0-py3-none-any.whl (56 kB)
Collecting regex==2020.10.15
  Using cached regex-2020.10.15.tar.gz (690 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting rich==12.4.4
  Using cached rich-12.4.4-py3-none-any.whl (232 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting toml==0.10.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting tqdm==4.64.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting typed-ast==1.4.1
  Using cached typed_ast-1.4.1.tar.gz (208 kB)
  Preparing metadata (setup.py) ... done
Collecting typing_extensions==4.2.0
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting update-checker==0.18.0
  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting websocket-client==1.3.2
  Using cached websocket_client-1.3.2-py3-none-any.whl (54 kB)
Collecting websockets==10.1
  Using cached websockets-10.1-cp310-cp310-win_amd64.whl (97 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Using legacy 'setup.py install' for moviepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for regex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for typed-ast, since package 'wheel' is not installed.
Installing collected packages: typed-ast, toml, regex, pyee, mypy-extensions, mccabe, commonmark, certifi, appdirs, websockets, websocket-client, urllib3, typing_extensions, six, pytube, python-dotenv, Pygments, pyflakes, pycodestyle, Pillow, pathspec, numpy, mutagen, imageio-ffmpeg, idna, greenlet, decorator, colorama, click, charset-normalizer, tqdm, rich, requests, playwright, imageio, flake8, black, update-checker, proglog, prawcore, gTTS, praw, moviepy
  Attempting uninstall: typed-ast
    Found existing installation: typed-ast 1.5.4
    Uninstalling typed-ast-1.5.4:
      Successfully uninstalled typed-ast-1.5.4
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error

  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast27.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\ast3.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\conversions.py -> build\lib.win-amd64-3.10\typed_ast
      copying typed_ast\__init__.py -> build\lib.win-amd64-3.10\typed_ast
      package init file 'ast3\tests\__init__.py' not found (or not a regular file)
      creating build\lib.win-amd64-3.10\typed_ast\tests
      copying ast3\tests\test_basics.py -> build\lib.win-amd64-3.10\typed_ast\tests
      running build_ext
      building '_ast27' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\ast27
      creating build\temp.win-amd64-3.10\Release\ast27\Custom
      creating build\temp.win-amd64-3.10\Release\ast27\Parser
      creating build\temp.win-amd64-3.10\Release\ast27\Python
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iast27/Include -IC:\Users\camus\AppData\Local\Programs\Python\Python310\include -IC:\Users\camus\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcast27/Custom/typed_ast.c /Fobuild\temp.win-amd64-3.10\Release\ast27/Custom/typed_ast.obj
      typed_ast.c
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(37): error C2143: syntax error: missing ')' before '*'
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(37): error C2081: 'PyArena': name in formal parameter list illegal
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(37): error C2143: syntax error: missing '{' before '*'
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(37): error C2059: syntax error: ')'
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(38): error C2143: syntax error: missing ')' before '*'
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(38): error C2081: 'PyArena': name in formal parameter list illegal
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(38): error C2143: syntax error: missing '{' before '*'
      C:\Users\camus\AppData\Local\Temp\pip-install-6bidab4x\typed-ast_a44f018867274e268e75b937c7a13e5a\ast27\Include\asdl.h(38): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(398): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(398): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(398): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(398): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(400): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(400): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(400): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(400): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(402): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(402): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(402): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(402): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(404): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(404): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(404): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(404): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(406): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(406): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(406): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(406): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(410): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(410): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(410): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(410): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(413): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(413): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(413): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(413): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(415): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(415): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(415): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(415): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(417): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(417): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(417): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(417): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(420): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(420): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(420): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(420): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(423): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(423): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(423): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(423): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(426): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(426): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(426): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(426): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(429): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(429): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(429): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(429): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(432): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(432): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(432): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(432): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(435): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(435): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(435): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(435): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(438): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(438): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(438): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(438): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(441): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(441): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(441): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(441): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(444): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(444): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(444): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(444): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(447): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(447): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(447): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(447): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(449): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(449): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(449): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(449): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(451): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(451): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(451): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(451): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(454): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(454): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(454): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(454): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(457): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(457): error C2081: 'PyArena': name in formal parameter list illegal
      ast27/Include\Python-ast.h(457): error C2143: syntax error: missing '{' before '*'
      ast27/Include\Python-ast.h(457): error C2059: syntax error: ')'
      ast27/Include\Python-ast.h(459): error C2143: syntax error: missing ')' before '*'
      ast27/Include\Python-ast.h(459): fatal error C1003: error count exceeds 100; stopping compilation
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\camus\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of typed-ast
  Moving to c:\users\camus\appdata\local\programs\python\python310\lib\site-packages\typed_ast-1.5.4.dist-info\
   from C:\Users\camus\AppData\Local\Programs\Python\Python310\Lib\site-packages\~yped_ast-1.5.4.dist-info
  Moving to c:\users\camus\appdata\local\programs\python\python310\lib\site-packages\typed_ast\
   from C:\Users\camus\AppData\Local\Programs\Python\Python310\Lib\site-packages\~yped_ast
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by elebumm** [comment]
Hoping that PR #31 fixes this. Going to close this in the meantime. If this still persists after #31 is merged in, feel free to reopen.
