### ISSUE TITLE
I am getting this error while downloading all dep and requirements 

### ISSUE THREAD

**Issue by muzammil-eng** [elebumm/RedditVideoMakerBot#980]
ERROR: Could not find a version that satisfies the requirement playwright==1.23.0 (from versions: none)
ERROR: No matching distribution found for playwright==1.23.0

**Comment by micziz** [comment]
Hi @muzammil-eng. It is probably caused by the requirements.txt. Cloud you please provide us with some more info like:

- Python version (can be accessed by typing `python --version` in the command line.
- Bot version. More tricky but remember what zip you downloaded.
- Os: The os is crucial to know if there is a bug. For example in arch linux (and based) playwright has some problems.
